import logging

from PIL import Image
from surya.recognition import batch_recognition

from schemas.ocr_models import PageLayout

logger = logging.getLogger(__name__)


def extract_text_from_layout(
    image: Image.Image,
    layout: PageLayout,
    rec_model,
    rec_processor,
) -> PageLayout:
    """Takes a pre-computed PageLayout (with geometric ColumnBlocks and empty TextLines).

    Uses Surya's recognition model to extract the actual characters for those boundaries.

    Args:
        image: The source high-res PIL Image.
        layout: The Pydantic PageLayout generated by `layout_parser.py`.
        rec_model: The loaded Surya text recognition model.
        rec_processor: The associated Surya image processor matching recognition.

    Returns:
        PageLayout: The exact same Pydantic object, but with the `text` and `confidence` fields populated.
    """
    # We need to build a flat list of all BoundingBoxes to send to Surya in one giant batch
    # for maximum GPU efficiency.
    all_bboxes = []

    # We also keep a flat reference list of the actual Pydantic TextLine objects
    # so we can inject the text back into them once Surya returns the batch results.
    line_references = []

    for column in layout.columns:
        for line in column.lines:
            all_bboxes.append(line.bbox.coordinates)
            line_references.append(line)

    if not all_bboxes:
        logger.warning(
            f"Page {layout.page_number} has no text boxes to process. Passing empty layout."
        )
        return layout

    logger.debug(
        f"Page {layout.page_number}: Running batched text recognition on {len(all_bboxes)} lines..."
    )

    # Execute Surya Recognition
    # languages=["am"] tells Surya to expect Amharic/Ge'ez Fidel script
    recognition_results = batch_recognition(
        [image], [[bbox] for bbox in all_bboxes], rec_model, rec_processor, languages=["am"]
    )[0]

    # Map the results back to the Pydantic objects
    for i, rec_line in enumerate(recognition_results.text_lines):
        # We mutate the specific Pydantic TextLine object directly in memory
        target_line = line_references[i]
        target_line.text = rec_line.text
        target_line.confidence = rec_line.confidence

    logger.info(f"Page {layout.page_number}: Text recognition successfully completed.")

    return layout
